"""user journey profiles and trip conversations

Revision ID: 96edbc1ddb95
Revises: d8ebc12ca084
Create Date: 2026-07-13 17:25:37.210029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96edbc1ddb95'
down_revision: Union[str, Sequence[str], None] = 'd8ebc12ca084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('user_journey_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('typical_use_cases', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('stated_dislikes', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('home_location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('work_location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('known_regular_routes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('driving_persona', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('preferred_convo_style', sa.String(length=20), server_default=sa.text("'brief'"), nullable=False),
    sa.Column('morning_routine_start_time', sa.Time(), nullable=True),
    sa.Column('typical_commute_duration_mins', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_geospatial_index('idx_user_journey_profiles_home_location', 'user_journey_profiles', ['home_location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_user_journey_profiles_work_location', 'user_journey_profiles', ['work_location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('trip_conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('preference_updates_extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trip_conversations_trip_id', 'trip_conversations', ['trip_id'], unique=False)
    op.create_index('idx_trip_conversations_user_id', 'trip_conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trip_conversations_user_id', table_name='trip_conversations')
    op.drop_index('idx_trip_conversations_trip_id', table_name='trip_conversations')
    op.drop_table('trip_conversations')
    op.drop_geospatial_index('idx_user_journey_profiles_work_location', table_name='user_journey_profiles', postgresql_using='gist', column_name='work_location')
    op.drop_geospatial_index('idx_user_journey_profiles_home_location', table_name='user_journey_profiles', postgresql_using='gist', column_name='home_location')
    op.drop_geospatial_table('user_journey_profiles')
    # ### end Alembic commands ###
