"""initial schema

Revision ID: d8ebc12ca084
Revises: 
Create Date: 2026-07-08 20:06:02.752089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8ebc12ca084'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('road_segments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('osm_way_id', sa.BigInteger(), nullable=True),
    sa.Column('geom', Geography(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('highway_type', sa.String(length=50), nullable=True),
    sa.Column('speed_limit_kph', sa.Integer(), nullable=True),
    sa.Column('lanes', sa.Integer(), nullable=True),
    sa.Column('one_way', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('last_verified_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('confidence_score', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_road_segments_geom', 'road_segments', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_geospatial_table('trips',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('origin', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('destination', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('suggested_route', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual_path_taken', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('implicit_signals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('explicit_feedback', sa.Text(), nullable=True),
    sa.Column('reward_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_trips_destination', 'trips', ['destination'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_trips_origin', 'trips', ['origin'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('idx_trips_user_id', 'trips', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('avoid_highways', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('avoid_tolls', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('avoid_left_turns', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('prefer_scenic', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('max_acceptable_detour_minutes', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('preference_vector', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    op.drop_index('idx_trips_user_id', table_name='trips')
    op.drop_geospatial_index('idx_trips_origin', table_name='trips', postgresql_using='gist', column_name='origin')
    op.drop_geospatial_index('idx_trips_destination', table_name='trips', postgresql_using='gist', column_name='destination')
    op.drop_geospatial_table('trips')
    op.drop_table('users')
    op.drop_geospatial_index('idx_road_segments_geom', table_name='road_segments', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('road_segments')
    # ### end Alembic commands ###
